# Generated by Django 5.1.5 on 2025-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_profile_activity_level_profile_cooking_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('diet_type', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('standard', 'Standard')], max_length=20)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('recipe_link', models.URLField(blank=True, max_length=500, null=True)),
                ('instructions', models.TextField()),
                ('diet_selected', models.BooleanField(default=False)),
                ('cooking_time', models.IntegerField(help_text='Cooking time in minutes')),
            ],
        ),
    ]
