# Generated by Django 5.1.5 on 2025-03-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_usermealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='diet_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cooking_time',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('eggitarian', 'Eggitarian'), ('mediterranean', 'Mediterranean'), ('vegan', 'Vegan'), ('detox', 'Detox Diet')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='diet_selection',
            field=models.CharField(default='default_diet', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='goal_selection',
            field=models.CharField(blank=True, choices=[('weight-loss', 'Lose Weight'), ('muscle-gain', 'Build Muscle'), ('get-lean', 'Get Lean'), ('maintain', 'Maintain Fitness'), ('strength', 'Increase Strength'), ('endurance', 'Build Endurance'), ('flexibility', 'Improve Flexibility'), ('sports', 'Sports Performance'), ('body-recomp', 'Body Recomposition'), ('powerlifting', 'Powerlifting'), ('calisthenics', 'Calisthenics'), ('general-health', 'General Health')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cooking_time_preference',
            field=models.CharField(blank=True, choices=[('<10', 'Less than 10 minutes'), ('10-20', '10 - 20 minutes'), ('20-30', '20 - 30 minutes'), ('30-45', '30 - 45 minutes'), ('>45', 'More than 45 minutes')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='snacks',
            field=models.ManyToManyField(blank=True, related_name='snack_meals', to='landing.mealplan'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='cooking_time',
            field=models.CharField(choices=[('<10', 'Less than 10 minutes'), ('10-20', '10 - 20 minutes'), ('20-30', '20 - 30 minutes'), ('30-45', '30 - 45 minutes'), ('>45', 'More than 45 minutes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('snacks', 'Snacks'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('eggitarian', 'Eggitarian'), ('mediterranean', 'Mediterranean'), ('vegan', 'Vegan'), ('detox', 'Detox Diet')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diet_selection',
            field=models.CharField(blank=True, choices=[('no-diet', 'No Diet at all'), ('keto', 'Keto'), ('fasting', 'Intermittent Fasting'), ('gluten-free', 'Gluten Free'), ('raw-food', 'Raw Food'), ('bulking', 'Bulking')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_selection',
            field=models.CharField(blank=True, choices=[('weight-loss', 'Lose Weight'), ('muscle-gain', 'Build Muscle'), ('get-lean', 'Get Lean'), ('maintain', 'Maintain Fitness'), ('strength', 'Increase Strength'), ('endurance', 'Build Endurance'), ('flexibility', 'Improve Flexibility'), ('sports', 'Sports Performance'), ('body-recomp', 'Body Recomposition'), ('powerlifting', 'Powerlifting'), ('calisthenics', 'Calisthenics'), ('general-health', 'General Health')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='lunch',
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast_meals', to='landing.mealplan'),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner_meals', to='landing.mealplan'),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch_meals', to='landing.mealplan'),
        ),
    ]
