# Generated by Django 5.1.7 on 2025-03-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_exercise_masterworkout_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rest_days',
            field=models.TextField(blank=True, null=True),
        ),
    ]
