# Generated by Django 5.1.7 on 2025-03-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_exercise_masterworkout_meal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
