# Generated by Django 5.1.7 on 2025-03-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_profile_bmi_profile_rest_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
