# Generated by Django 5.1.7 on 2025-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_delete_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
