# Generated by Django 5.1.5 on 2025-03-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_meal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
