# Generated by Django 5.1.5 on 2025-03-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_exercise_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stretching_preference',
            field=models.BooleanField(default=False),
        ),
    ]
