# Generated by Django 5.1.7 on 2025-04-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_curency_plan_currency'),
        ('users', '0003_profile_stretching_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan'),
        ),
    ]
