# Generated by Django 5.1.7 on 2025-04-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_selected_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
