# Generated by Django 5.1.7 on 2025-04-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curency', models.CharField(default='usd', max_length=10)),
                ('interval', models.CharField(default='month', max_length=10)),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('price_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
