# Generated by Django 5.1.7 on 2025-04-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='curency',
            new_name='currency',
        ),
    ]
