from django.core.management.base import BaseCommand
from meals.models import Meal


class Command(BaseCommand):
    help = "Insert restaurant data into the database"

    def handle(self, *args, **kwargs):
        data = [
            {
                "id": 1,
                "name": "Ramen Misoya",
                "location": "2065A Rue Bishop",
                "price": 15,
            },
            {
                "id": 2,
                "name": "Maison ChaiShai",
                "location": "2005 Rue Bishop",
                "price": 12,
            },
            {
                "id": 3,
                "name": "Burger Bar Crescent",
                "location": "1465 Crescent Street",
                "price": 18,
            },
            {
                "id": 4,
                "name": "Wienstein & Gavino's",
                "location": "1434 Crescent Street",
                "price": 20,
            },
            {
                "id": 5,
                "name": "Chez Devi",
                "location": "1450 Crescent Street",
                "price": 22,
            },
            {
                "id": 6,
                "name": "Insiders - Cafe & Cowork",
                "location": "2067 Rue Crescent, Suite 205",
                "price": 10,
            },
            {
                "id": 7,
                "name": "Boustan",
                "location": "2020A Crescent Street",
                "price": 12,
            },
            {
                "id": 8,
                "name": "Cafe Aunja",
                "location": "1448 Sherbrooke Street West",
                "price": 8,
            },
            {
                "id": 9,
                "name": "Sir Winston Churchill Pub Complex",
                "location": "1455-59 Crescent Street",
                "price": 15,
            },
            {"id": 10, "name": "Mandy's", "location": "2067 Rue Crescent", "price": 14},
            {
                "id": 11,
                "name": "Nespresso Boutique",
                "location": "2045 Rue Crescent",
                "price": 5,
            },
            {
                "id": 12,
                "name": "Cafe Myriade",
                "location": "1432 Rue Mackay",
                "price": 7,
            },
            {
                "id": 13,
                "name": "Le Warehouse",
                "location": "1446 Rue Crescent",
                "price": 10,
            },
            {
                "id": 14,
                "name": "La Panthère Verte",
                "location": "2153 Rue Mackay",
                "price": 12,
            },
            {
                "id": 15,
                "name": "Le Poke Bar",
                "location": "2153 Rue Crescent",
                "price": 15,
            },
            {
                "id": 16,
                "name": "McKibbin's Irish Pub",
                "location": "1426 Rue Bishop",
                "price": 16,
            },
            {
                "id": 17,
                "name": "Marcus Restaurant + Terrace",
                "location": "1440 Rue de la Montagne",
                "price": 30,
            },
            {
                "id": 18,
                "name": "Cafe Il Cortile",
                "location": "1442 Rue Sherbrooke Ouest",
                "price": 20,
            },
            {
                "id": 19,
                "name": "Restaurant L'autre Saison",
                "location": "2137 Rue Crescent",
                "price": 25,
            },
            {
                "id": 20,
                "name": "Notre-Boeuf-de-Grâce",
                "location": "1388 Boulevard de Maisonneuve Ouest",
                "price": 15,
            },
            {"id": 21, "name": "Tuscolo", "location": "1466 Rue Crescent", "price": 18},
            {
                "id": 22,
                "name": "Dirty Dogs",
                "location": "25 Avenue du Mont-Royal E",
                "price": 12,
            },
            {
                "id": 23,
                "name": "Yen Cuisine Japonaise",
                "location": "2157 Rue Mackay",
                "price": 20,
            },
            {
                "id": 24,
                "name": "Restaurant L'Académie Crescent",
                "location": "2100 Rue Crescent",
                "price": 22,
            },
            {
                "id": 25,
                "name": "Ziggy's Pub",
                "location": "1470 Rue Crescent",
                "price": 10,
            },
            {"id": 26, "name": "Java U", "location": "1455 Rue Guy", "price": 8},
            {
                "id": 27,
                "name": "Brass Door Pub",
                "location": "2171 Rue Crescent",
                "price": 12,
            },
            {
                "id": 28,
                "name": "Ristorante Beatrice",
                "location": "1504 Rue Sherbrooke Ouest",
                "price": 28,
            },
            {
                "id": 29,
                "name": "Ganadara",
                "location": "1862 Boulevard de Maisonneuve Ouest",
                "price": 14,
            },
            {
                "id": 30,
                "name": "Restaurant Nilufar",
                "location": "1923 Rue Sainte-Catherine Ouest",
                "price": 9,
            },
            {
                "id": 31,
                "name": "Sammi & Soupe Dumpling",
                "location": "1909 Rue Sainte-Catherine Ouest",
                "price": 13,
            },
            {
                "id": 32,
                "name": "Wawel Patisserie",
                "location": "1413 Rue Saint-Marc",
                "price": 6,
            },
            {
                "id": 33,
                "name": "Thali Cuisine Indienne",
                "location": "1409 Rue Saint-Marc",
                "price": 12,
            },
            {"id": 34, "name": "Picks", "location": "1407 Rue Saint-Marc", "price": 11},
            {
                "id": 35,
                "name": "Al-Baghdadi Pastry",
                "location": "1624 Avenue Lincoln",
                "price": 8,
            },
            {
                "id": 36,
                "name": "I Am Pho",
                "location": "1444 Rue Saint Mathieu",
                "price": 14,
            },
            {
                "id": 37,
                "name": "Qing Hua Dumpling",
                "location": "1675 Boulevard de Maisonneuve Ouest",
                "price": 13,
            },
            {
                "id": 38,
                "name": "Otto Yakitori Izakaya",
                "location": "1441 Rue Saint Mathieu",
                "price": 18,
            },
            {
                "id": 39,
                "name": "Antep Kebap",
                "location": "1626 Boulevard de Maisonneuve Ouest",
                "price": 10,
            },
            {
                "id": 40,
                "name": "Il Panino - Café Méditerranéo",
                "location": "1435 Rue Guy",
                "price": 9,
            },
            {
                "id": 41,
                "name": "Ramen Misoya Montreal",
                "location": "2065 Rue Bishop",
                "price": 15,
            },
            {
                "id": 42,
                "name": "Café Myriade",
                "location": "1432 Rue Mackay",
                "price": 7,
            },
            {
                "id": 43,
                "name": "Café Aunja",
                "location": "1448 Rue Sherbrooke Ouest",
                "price": 8,
            },
            {
                "id": 44,
                "name": "Garage Beirut",
                "location": "1238 Rue Mackay",
                "price": 12,
            },
            {
                "id": 45,
                "name": "Joe's Panini",
                "location": "1404 Rue Drummond",
                "price": 8,
            },
            {
                "id": 47,
                "name": "KINTON RAMEN BISHOP",
                "location": "1211 Rue Bishop",
                "price": 15,
            },
            {"id": 48, "name": "Ryu", "location": "1474 Rue Peel", "price": 25},
            {
                "id": 49,
                "name": "Parma Café",
                "location": "1202 Rue Bishop",
                "price": 12,
            },
            {
                "id": 50,
                "name": "Koa Lua Sainte Catherine",
                "location": "1446 Rue Sainte-Catherine",
                "price": 14,
            },
            {
                "id": 51,
                "name": "Shaughnessy Café",
                "location": "1455 Rue Lambert Closse",
                "price": 10,
            },
            {
                "id": 52,
                "name": "Otto Yakitori Izakaya",
                "location": "1441 Rue Saint Mathieu",
                "price": 18,
            },
            {
                "id": 53,
                "name": "Deville Dinerbar",
                "location": "1425 Rue Stanley",
                "price": 20,
            },
            {
                "id": 54,
                "name": "Gyu-Kaku Japanese BBQ",
                "location": "1255 Rue Crescent",
                "price": 28,
            },
            {
                "id": 55,
                "name": "Le Pois Penché",
                "location": "1230 Boulevard de Maisonneuve Ouest",
                "price": 22,
            },
            {
                "id": 56,
                "name": "Café Holt Ogilvy",
                "location": "1307 Rue Sainte-Catherine Ouest",
                "price": 15,
            },
            {
                "id": 57,
                "name": "Sel Noir Steakhouse",
                "location": "1228 Rue Sherbrooke Ouest",
                "price": 35,
            },
            {
                "id": 58,
                "name": "Maison Boulud",
                "location": "1228 Rue Sherbrooke Ouest",
                "price": 40,
            },
            {
                "id": 59,
                "name": "Koa Lua",
                "location": "1446 Rue Sainte-Catherine Ouest",
                "price": 14,
            },
            {
                "id": 60,
                "name": "Escondite",
                "location": "1206 Avenue Union",
                "price": 16,
            },
            {
                "id": 61,
                "name": "Biiru",
                "location": "1433 Rue City Councillors",
                "price": 18,
            },
            {"id": 62, "name": "Habanera", "location": "1216 Rue Bishop", "price": 14},
            {
                "id": 63,
                "name": "Kampai Garden",
                "location": "1616 Rue Sainte-Catherine Ouest",
                "price": 20,
            },
            {
                "id": 64,
                "name": "Imadake Izakaya",
                "location": "4006 Rue Sainte-Catherine Ouest",
                "price": 22,
            },
            {
                "id": 65,
                "name": "Kazu",
                "location": "1862 Rue Sainte-Catherine Ouest",
                "price": 15,
            },
            {
                "id": 66,
                "name": "Mon Ami",
                "location": "1831 Rue Sainte-Catherine Ouest",
                "price": 13,
            },
            {
                "id": 67,
                "name": "Pikolo Espresso Bar",
                "location": "3418 Avenue du Parc",
                "price": 8,
            },
            {"id": 68, "name": "Café Parvis", "location": "433 Rue Mayor", "price": 12},
            {
                "id": 69,
                "name": "Tommy Café",
                "location": "200 Rue Notre-Dame Ouest",
                "price": 10,
            },
            {
                "id": 70,
                "name": "Café Olimpico",
                "location": "419 Rue Saint-Vincent",
                "price": 9,
            },
            {
                "id": 71,
                "name": "La Finca Café",
                "location": "1067 Rue de Bleury",
                "price": 11,
            },
            {
                "id": 72,
                "name": "Café Humble Lion",
                "location": "904 Rue Sherbrooke Ouest",
                "price": 7,
            },
            {
                "id": 73,
                "name": "Muru Crêpe",
                "location": "362 Rue Notre-Dame Ouest",
                "price": 13,
            },
            {
                "id": 74,
                "name": "Café Vasco da Gama",
                "location": "1472 Rue Peel",
                "price": 14,
            },
            {
                "id": 75,
                "name": "Mandy's Salades Gourmandes",
                "location": "2067 Rue Crescent",
                "price": 14,
            },
            {
                "id": 76,
                "name": "La Panthère Verte",
                "location": "2153 Rue Mackay",
                "price": 12,
            },
            {
                "id": 77,
                "name": "Lola Rosa",
                "location": "4581 Avenue du Parc",
                "price": 16,
            },
            {
                "id": 78,
                "name": "Copper Branch",
                "location": "1245 Rue Bishop",
                "price": 14,
            },
            {
                "id": 79,
                "name": "Lov",
                "location": "1232 Rue de la Montagne",
                "price": 20,
            },
            {
                "id": 80,
                "name": "Crudessence",
                "location": "2157 Rue Mackay",
                "price": 18,
            },
            {
                "id": 81,
                "name": "Aux Vivres",
                "location": "4631 Boulevard Saint-Laurent",
                "price": 15,
            },
            {
                "id": 82,
                "name": "Sushi Momo",
                "location": "3609 Rue Saint-Denis",
                "price": 22,
            },
            {
                "id": 83,
                "name": "ChuChai",
                "location": "4088 Rue Saint-Denis",
                "price": 25,
            },
            {
                "id": 84,
                "name": "La Belle et La Boeuf",
                "location": "1620 Rue Sainte-Catherine Ouest",
                "price": 18,
            },
            {
                "id": 85,
                "name": "Jack Saloon",
                "location": "1211 Rue de la Montagne",
                "price": 20,
            },
            {
                "id": 86,
                "name": "Les 3 Brasseurs",
                "location": "732 Rue Sainte-Catherine Ouest",
                "price": 16,
            },
            {
                "id": 87,
                "name": "Bâton Rouge Steakhouse & Bar",
                "location": "1050 Rue de la Montagne",
                "price": 28,
            },
            {
                "id": 88,
                "name": "Le Keg Steakhouse + Bar",
                "location": "5 Place Ville Marie",
                "price": 35,
            },
            {
                "id": 89,
                "name": "Moishes Steakhouse",
                "location": "3961 Boulevard Saint-Laurent",
                "price": 45,
            },
            {
                "id": 90,
                "name": "Gibbys",
                "location": "298 Place d'Youville",
                "price": 40,
            },
            {
                "id": 91,
                "name": "Joe Beef",
                "location": "2491 Rue Notre-Dame Ouest",
                "price": 50,
            },
        ]

        for item in data:
            Meal.objects.create(**item)

        self.stdout.write(self.style.SUCCESS("Successfully inserted restaurant data"))
