# Generated by Django 5.1.5 on 2025-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('Warm Up', 'Warm Up'), ('Main Exercise', 'Main Exercise'), ('Cool Down', 'Cool Down')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
