# Generated by Django 5.1.6 on 2025-03-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workoutexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='impact_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
