# Generated by Django 5.1.5 on 2025-04-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_exercise_impact_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body_part', models.CharField(choices=[('Full Body', 'Full Body'), ('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Core', 'Core'), ('Glutes', 'Glutes')], default='Full Body', max_length=50)),
                ('description', models.TextField(default='')),
                ('exercise_type', models.CharField(choices=[('Strength', 'Strength'), ('Cardio', 'Cardio'), ('Core', 'Core'), ('Power', 'Power'), ('Plyometric', 'Plyometric'), ('Yoga', 'Yoga')], default='Strength', max_length=20)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('impact_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('instructions', models.TextField(default='')),
                ('duration', models.IntegerField(default=10, help_text='Duration in minutes')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=10)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise Library',
                'verbose_name_plural': 'Exercise Library',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='body_part',
            field=models.CharField(default='Full Body', max_length=100),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='impact_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='duration',
            field=models.IntegerField(default=10, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise_type',
            field=models.CharField(choices=[('Warm Up', 'Warm Up'), ('Main Exercise', 'Main Exercise'), ('Cool Down', 'Cool Down'), ('Strength', 'Strength'), ('Cardio', 'Cardio'), ('Core', 'Core'), ('Power', 'Power'), ('Plyometric', 'Plyometric'), ('Yoga', 'Yoga')], default='Main Exercise', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.IntegerField(default=3),
        ),
    ]
