# Generated by Django 5.1.7 on 2025-03-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('snacks', 'Snacks'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('diet_selection', models.CharField(default='default_diet', max_length=100)),
                ('diet_preference', models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('eggitarian', 'Eggitarian'), ('mediterranean', 'Mediterranean'), ('vegan', 'Vegan'), ('detox', 'Detox Diet')], max_length=20, null=True)),
                ('goal_selection', models.CharField(blank=True, choices=[('weight-loss', 'Lose Weight'), ('muscle-gain', 'Build Muscle'), ('get-lean', 'Get Lean'), ('maintain', 'Maintain Fitness'), ('strength', 'Increase Strength'), ('endurance', 'Build Endurance'), ('flexibility', 'Improve Flexibility'), ('sports', 'Sports Performance'), ('body-recomp', 'Body Recomposition'), ('powerlifting', 'Powerlifting'), ('calisthenics', 'Calisthenics'), ('general-health', 'General Health')], max_length=50, null=True)),
                ('cooking_time', models.CharField(choices=[('<10', 'Less than 10 minutes'), ('10-20', '10 - 20 minutes'), ('20-30', '20 - 30 minutes'), ('30-45', '30 - 45 minutes'), ('>45', 'More than 45 minutes')], max_length=10)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('recipe_link', models.URLField(blank=True, max_length=500, null=True)),
                ('instructions', models.TextField()),
                ('diet_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.ManyToManyField(blank=True, related_name='breakfast_meals', to='meals.mealplan')),
                ('dinner', models.ManyToManyField(blank=True, related_name='dinner_meals', to='meals.mealplan')),
                ('lunch', models.ManyToManyField(blank=True, related_name='lunch_meals', to='meals.mealplan')),
                ('snacks', models.ManyToManyField(blank=True, related_name='snack_meals', to='meals.mealplan')),
            ],
        ),
    ]
