# Generated by Django 5.1.5 on 2025-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
