# Generated by Django 5.1.5 on 2025-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20250320_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='meal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
